### ISSUE TITLE
Keyword `τ` seems to have no effect

### ISSUE THREAD

**Issue by Datseris** [kahaaga/TransferEntropy.jl#56]
I am doing
```julia
    Td2p = transferentropy(dIBI, pIBI, estimator, 1, 1, 1; τ = 1)
    Tp2d = transferentropy(pIBI, dIBI, estimator, 1, 1, 1; τ = 1)
```
and I change `τ` from 1 to 2. I get _identical_ numbers for my TE, which I don't think is reasonable.

**Comment by kahaaga** [comment]
Hey there! As far as I can see, you are using a total dimension of 3 (all three embedding dimension parameters are 1, and sum to 3). This only includes the present value of the target variable for that component of the embedding (i.e. no history). For `τ` to have an effect, the embedding parameter controlling the dimension of the present/past of the target variable needs to be >= 2, so that both the present value _and_ past values are included in the embedding.

Assume `X` is the source time series and `Y` is the target time series, and you compute transfer entropy from `X` to `Y`. With embedding dimension `k + l + m = 3`, you do an embedding `E = {x(t), y(t), y(t+eta)}`, where `eta` is the forward prediction lag. Changing `τ` thus doesn't affect anything. If you increase the dimension of the target present/past component of the embedding to 2, you would have a total dimension of 4, and the embedding would be `E = {x(t), y(t-τ), y(t), y(t+eta)}`. In this case `τ` does affect the value you get, because you would also pick historical values together with the present value of the target.

 In the current version, `τ` only affects that component of the embedding containing the present/past of the target variable. With the new syntax we agreed on coming, there will be a `τ` for each component of the embedding (`S`, `T`, ... for the dimension and `τS`, `τT`, ... for the corresponding lags).

Does that make sense? Let me know if you still get identical numbers if increasing the dimensionality of the present/past of the target variable.

**Comment by Datseris** [comment]
Yes, you are correct. I forgot that here the numbers are the final dimension (I had in mind the γ we use in dynamical systems, which is the amount of delays included)
